services:

  # -------------------------------
  # 1) Keycloak
  # -------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Use Postgres for the Keycloak database:     
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloakdb
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpass
      # "start-dev" runs Keycloak in dev mode, but still uses Postgres instead of the embedded H2  
      # "start" for production mode
    command: ["start-dev"]  
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"
    networks:
      - auth-network

  # -------------------------------
  # 2) Postgres DB for Keycloak
  # -------------------------------
  keycloak-db:
    image: postgres:15.2
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloakdb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/keycloak_db_data:/var/lib/postgresql/data    
    networks:
      - auth-network
     
  # -------------------------------
  # 3) Postgres DB for Authentication
  # -------------------------------
  auth-db:
    image: postgres:15.2
    container_name: auth-db
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/auth_db_data:/var/lib/postgresql/data
    networks:
      - auth-network

    # image: mcr.microsoft.com/mssql/server:2022-latest
    # container_name: auth-db
    # environment:
    #   SA_PASSWORD: "YourStrongPassw0rd"
    #   ACCEPT_EULA: "Y"
    #   # Additional config can go here
    # ports:
    #   - "1433:1433"  # Expose SQL Server on localhost:1433
    # # If you want a named volume for data persistence:
    # # volumes:
    # #   - sql_data:/var/opt/mssql


  # -------------------------------
  # 4) Authentication 
  # -------------------------------
  Authentication.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: src/API/Dockerfile   
    environment:
      # .NET environment
      ASPNETCORE_ENVIRONMENT: "Development"

      # Keycloak config - point the microservice to the internal Keycloak address
      #KEYCLOAK_URL: "http://keycloak:8080"
      #KEYCLOAK_REALM: "DMSRealm"
      #KEYCLOAK_CLIENT_ID: "myclient"
      #KEYCLOAK_CLIENT_SECRET: "mysecret" # or manage secrets via a safer method

      # Example DB connection string for Postgres
      #DB_CONNECTION_STRING: "Host=auth-db;Port=5432;Database=authdb;User ID=auth;Password=auth"
      #DB_CONNECTION_STRING: "Server=sqlserver;Database=authdb;User ID=sa;Password=auth;TrustServerCertificate=True"

    depends_on:
      - keycloak
      - auth-db
    ports:
      - "5032:8070"      
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge  



