// <auto-generated />
using System;
using System.Collections.Generic;
using Authentication.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Authentication.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122135741_AddIndexes_Whitelist")]
    partial class AddIndexes_Whitelist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Authentication.Domain.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MfaType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mfa_type");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_configuration");

                    b.ToTable("Configuration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MfaType = 0,
                            ModifiedAt = new DateTime(2026, 1, 22, 13, 57, 40, 754, DateTimeKind.Utc).AddTicks(3504)
                        });
                });

            modelBuilder.Entity("Authentication.Domain.Entities.EmailWhitelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_email_whitelist");

                    b.HasIndex("Type", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_email_whitelist_type_value");

                    b.ToTable("EmailWhitelist", (string)null);
                });

            modelBuilder.Entity("Authentication.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_id");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean")
                        .HasColumnName("allowed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("EndPoints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("end_points");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<Guid>("KeycloakRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_role_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<List<string>>("Urls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("urls");

                    b.HasKey("Id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("KeycloakRoleId", "HttpMethod", "Allowed")
                        .HasDatabaseName("ix_role_permissions_keycloak_role_id_http_method_allowed");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Authentication.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("KeycloakUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_user_id");

                    b.Property<int>("MfaType")
                        .HasColumnType("integer")
                        .HasColumnName("mfa_type");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted")
                        .HasFilter("IsDeleted = false");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 22, 13, 57, 40, 754, DateTimeKind.Utc).AddTicks(3377),
                            IsAdmin = false,
                            IsDeleted = false,
                            KeycloakUserId = new Guid("255938e1-6a58-4ceb-b7b7-79670966958f"),
                            MfaType = 0,
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("Authentication.Domain.Entities.UserTotpSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Base32Secret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base32secret");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("KeycloakUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_user_id");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_user_totp_secrets");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_totp_secrets_keycloak_user_id");

                    b.ToTable("UserTotpSecrets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
